AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  Users:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: lambdas/users/dist/index.handler 
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API endpoint URL for dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
