AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  Users:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/users/dist
      Runtime: nodejs20.x
      Handler: index.handler 
      Layers:
        - !Ref CommonDependencies
      Architectures:
        - x86_64
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            Path: /users/
            Method: GET
        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
        

  CommonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: shared/common.zip

Outputs:
  WebEndpoint:
    Description: "API endpoint URL for dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
